### ISSUE TITLE
[Bug]: htmlwidgets

### ISSUE THREAD

**Issue by Andryas** [Appsilon/reactable.extras#52]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Project Version

0.2.0

### Platform and OS Version

macOS 14.1.2

### What happened?

When I ran the example given in the README with the htmlwidgets version 1.6.3, the buttons weren't showing up; when I updated the package version to 1.6.4, the issue was fixed. It's hard to detect this because there wasn't any error; it just didn't show up, so adding it to the project's dependencies would be nice.

Thanks

### Steps to reproduce

install the htmlwidgets@1.6.3

### Expected behavior

The buttons wont show up

### Attachments

 With the htmlwidgets 1.6.4

<img width="1302" alt="Screenshot 2023-12-18 at 7 30 43 AM" src="https://github.com/Appsilon/reactable.extras/assets/24782390/e4895eec-149d-4176-8da4-f1ea8bb80479">

Using renv and setting to 1.6.3

<img width="1294" alt="Screenshot 2023-12-18 at 7 36 39 AM" src="https://github.com/Appsilon/reactable.extras/assets/24782390/9f7ccb4e-70ce-4407-bb31-3ae99538d3ad">

**Comment by jakubnowicki** [comment]
Hi @Andryas ,
Thank you for sending us the issue. `reactable.extras` works fine with lower versions of `htmlwidgets` (<= 1.6.2). For more details regarding the problem, check out this issue: #48. As the `DESCRIPTION` does not allow excluding a single version of a package, we are not able to include this.
